USE DataWarehouse;
GO


-- =====================================================
-- 1. DATABASE EXPLORATION
-- Check available tables and columns
-- =====================================================

SELECT *
FROM DataWarehouse.INFORMATION_SCHEMA.TABLES;


SELECT *
FROM DataWarehouse.INFORMATION_SCHEMA.COLUMNS;


-- Check customer table structure
SELECT *
FROM DataWarehouse.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';



-- =====================================================
-- 2. DIMENSION EXPLORATION
-- Understand customer and product dimensions
-- =====================================================


-- List all available customer countries
SELECT DISTINCT
    country
FROM DataWarehouse.gold.dim_customers;


-- List all available customer genders
SELECT DISTINCT
    gender
FROM DataWarehouse.gold.dim_customers;


-- Explore product hierarchy
-- Category -> Subcategory -> Product
SELECT DISTINCT
    category,
    subcategory,
    product_name
FROM DataWarehouse.gold.dim_products
ORDER BY
    category,
    subcategory,
    product_name;



-- =====================================================
-- 3. DATE EXPLORATION
-- Understand data coverage and time periods
-- =====================================================


-- Find sales date range
SELECT
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(
        YEAR,
        MIN(order_date),
        MAX(order_date)
    ) AS order_range_years
FROM DataWarehouse.gold.fact_sales;


-- Find customer birthdate range
SELECT
    MIN(birthdate) AS oldest_customer,
    MAX(birthdate) AS youngest_customer
FROM DataWarehouse.gold.dim_customers;


-- Calculate customer age
SELECT
    customer_id,
    first_name,
    last_name,
    birthdate,
    DATEDIFF(YEAR, birthdate, GETDATE()) AS age
FROM DataWarehouse.gold.dim_customers;



-- =====================================================
-- 4. MEASURE EXPLORATION
-- Calculate overall business KPIs
-- =====================================================


-- Total revenue generated
SELECT
    SUM(sales_amount) AS total_sales
FROM DataWarehouse.gold.fact_sales;


-- Total quantity sold
SELECT
    SUM(quantity) AS total_quantity
FROM DataWarehouse.gold.fact_sales;


-- Average selling price
SELECT
    AVG(price) AS average_price
FROM DataWarehouse.gold.fact_sales;


-- Total number of orders
SELECT
    COUNT(DISTINCT order_number) AS total_orders
FROM DataWarehouse.gold.fact_sales;


-- Total number of products
SELECT
    COUNT(DISTINCT product_key) AS total_products
FROM DataWarehouse.gold.dim_products;


-- Total registered customers
SELECT
    COUNT(DISTINCT customer_key) AS total_customers
FROM DataWarehouse.gold.dim_customers;


-- Customers who made purchases
SELECT
    COUNT(DISTINCT customer_key) AS customers_with_orders
FROM DataWarehouse.gold.fact_sales;



-- =====================================================
-- 5. MAGNITUDE EXPLORATION
-- Analyze business distribution
-- =====================================================


-- Customer count by country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM DataWarehouse.gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Customer count by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM DataWarehouse.gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Product count by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM DataWarehouse.gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Average product cost by category
SELECT
    category,
    AVG(cost) AS average_cost
FROM DataWarehouse.gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


-- Revenue by product category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM DataWarehouse.gold.fact_sales f
LEFT JOIN DataWarehouse.gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Revenue generated by each customer
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM DataWarehouse.gold.dim_customers c
LEFT JOIN DataWarehouse.gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- Quantity sold by country
SELECT
    c.country,
    SUM(f.quantity) AS total_quantity_sold
FROM DataWarehouse.gold.dim_customers c
LEFT JOIN DataWarehouse.gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_quantity_sold DESC;



-- =====================================================
-- 6. RANKING EXPLORATION
-- Identify best and worst performers
-- =====================================================


-- Top 5 products by revenue
SELECT TOP 5
    p.product_id,
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM DataWarehouse.gold.fact_sales f
LEFT JOIN DataWarehouse.gold.dim_products p
ON f.product_key = p.product_key
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_revenue DESC;


-- Bottom 5 products by revenue
SELECT TOP 5
    p.product_id,
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM DataWarehouse.gold.fact_sales f
LEFT JOIN DataWarehouse.gold.dim_products p
ON f.product_key = p.product_key
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_revenue ASC;


-- Top 10 customers by revenue
SELECT TOP 10
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM DataWarehouse.gold.fact_sales f
LEFT JOIN DataWarehouse.gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- Customers with the fewest orders
SELECT TOP 3
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT f.order_number) AS total_orders
FROM DataWarehouse.gold.fact_sales f
LEFT JOIN DataWarehouse.gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_orders ASC;