USE DataWarehouse;
GO

-- =============================================================================
-- Create Report: gold.report_customers
-- Purpose: This report consolidates key customer metrics and behaviors.
-- =============================================================================

IF OBJECT_ID('gold.report_customers', 'V') IS NOT NULL
DROP VIEW gold.report_customers;
GO


CREATE VIEW gold.report_customers AS

WITH base_query AS
(
    /*
    ============================================================================
    1. Base Query
    Retrieves core customer and sales columns from fact and dimension tables
    ============================================================================
    */

    SELECT

        -- Sales information
        f.order_number,
        f.product_key,
        f.order_date,
        f.sales_amount,
        f.quantity,

        -- Customer information
        c.customer_id,
        c.customer_number,
        c.first_name,
        c.last_name,

        -- Create full customer name
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,

        -- Customer demographics
        c.country,
        c.gender,
        c.marital_status,
        c.birthdate,

        -- Calculate customer age
        DATEDIFF(YEAR, c.birthdate, GETDATE()) AS age


    FROM DataWarehouse.gold.fact_sales AS f

    LEFT JOIN DataWarehouse.gold.dim_customers AS c

        -- Join fact table with customer dimension
        ON f.customer_key = c.customer_key


    -- Remove records without order dates
    WHERE f.order_date IS NOT NULL
),



customer_aggregation AS
(
    /*
    ============================================================================
    2. Customer Aggregations
    Summarizes sales behavior at customer level
    ============================================================================
    */

    SELECT

        customer_id,
        customer_number,
        customer_name,
        country,
        gender,
        marital_status,
        age,


        -- Count number of unique orders
        COUNT(DISTINCT order_number) AS total_orders,


        -- Total revenue generated by customer
        SUM(sales_amount) AS total_sales,


        -- Total quantity purchased
        SUM(quantity) AS total_quantity,


        -- Number of different products purchased
        COUNT(DISTINCT product_key) AS total_products,


        -- Most recent purchase date
        MAX(order_date) AS last_order_date,


        -- Customer relationship duration in months
        DATEDIFF(
            MONTH,
            MIN(order_date),
            MAX(order_date)
        ) AS lifespan


    FROM base_query


    GROUP BY

        customer_id,
        customer_number,
        customer_name,
        country,
        gender,
        marital_status,
        age
)



/*
============================================================================
3. Final Customer Report
Adds customer segmentation and additional KPIs
============================================================================
*/

SELECT


    -- Customer details
    customer_id,
    customer_number,
    customer_name,
    country,
    gender,
    marital_status,
    age,


    -- Age category
    CASE
        WHEN age < 20 THEN 'Under 20'
        WHEN age BETWEEN 20 AND 29 THEN '20-29'
        WHEN age BETWEEN 30 AND 39 THEN '30-39'
        WHEN age BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50 and Above'
    END AS age_group,


    -- Customer value segmentation
    CASE
        WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
        WHEN lifespan >= 12 THEN 'Regular'
        ELSE 'New'
    END AS customer_segment,


    -- Purchase behavior
    last_order_date,


    -- Months since last purchase
    DATEDIFF(
        MONTH,
        last_order_date,
        GETDATE()
    ) AS recency,


    -- Sales metrics
    total_orders,
    total_sales,
    total_quantity,
    total_products,
    lifespan,


    -- Average Order Value (AOV)
    CASE
        WHEN total_orders = 0 THEN 0
        ELSE total_sales / total_orders
    END AS avg_order_value,


    -- Average Monthly Spend
    CASE
        WHEN lifespan = 0 THEN total_sales
        ELSE total_sales / lifespan
    END AS avg_monthly_spend


FROM customer_aggregation;
GO